apiVersion: 1
datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus # VictoriaMetrics is compatible to Prometheus API
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true