FROM postgres:latest
# Set environment variables
ENV POSTGRES_USER=gamestudio
ENV POSTGRES_PASSWORD=gamestudio
ENV POSTGRES_DB=gamestudiodb

# Copy the initialization script
# COPY init.sql /docker-entrypoint-initdb.d/
# COPY drop.sql /docker-entrypoint-initdb.d/

# Open port 5432 for PostgreSQL
EXPOSE 5432


